<br>


<!-- Google Analytics -->
<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-75650032-1', 'auto');
	  ga('send', 'pageview');
</script>
 <!-- Google Analytics -->

<!-- Footer -->
 <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
		© 2020 Copyright: &copy; <a href="https://www.ardupilot.org/"> ArduPilot.org</a>
    </div>
  </footer>  
<!-- Footer -->



 
  
  



